language: node_js
node_js:
  - '10'
services:
  - mongodb

cache:
  yarn: true
  directories:
    - library/common/node_modules

before_install:
  - cd library/common
  # - sleep 15

install:
  - yarn install

script:
  - yarn lint
  - mongo main --eval 'db.createUser({user:"admin",pwd:"fccdbo123!",roles:["readWrite", "dbAdmin"]});'
  - yarn build
  - yarn test
