language: node_js
node_js:
  - '10'
notifications:
  email: false

cache:
  yarn: true
  directories:
    - library/common/node_modules
    - job/node_modules

install:
  - yarn --cwd './library/common' install
  - yarn --cwd './job' install

script:
  - yarn --cwd './library/common' test
  - yarn --cwd './job' test
