version: '3'
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - '$PWD/mosquitto.conf:/mosquitto/config/mosquitto.conf'
      # - '$PWD/ssl/:/mosquitto/ssl/'

networks:
  default:
    external:
      name: database_backend